# Generated by Django 5.2 on 2025-11-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="avatars/"
            ),
        ),
    ]
