WINTER_BALL_DANCES = [
    {"name": "Полонез", "level": "Начальный", "has_partner": False},
    {"name": "Большой фигурный вальс", "level": "Продвинутый", "has_partner": False},
    {"name": "Кадриль «Летучая мышь»", "level": "Продвинутый", "has_partner": False},
    {"name": "Богемская полька", "level": "Начальный", "has_partner": False},
    {"name": "Вальс «Огонек Свечи»", "level": "Начальный", "has_partner": False},
    {"name": "КД «Три орешка для Золушки»", "level": "Начальный", "has_partner": False},
    {"name": "Канон-галапад Кадриль", "level": "Продвинутый", "has_partner": False},
    {"name": "Вальс «Паганини»", "level": "Продвинутый", "has_partner": False},
    {"name": "Катильон с цветком", "level": "Начальный", "has_partner": False},
    {"name": "Вальс «Нежность»", "level": "Средний", "has_partner": False},
    {"name": "Полька «Диабло»", "level": "Средний", "has_partner": False},
    {"name": "КД «Зимний Сон»", "level": "Начальный", "has_partner": False},
    {"name": "Фри Массон", "level": "Продвинутый", "has_partner": False},
    {"name": "Вальс «Сердце зимы»", "level": "Средний", "has_partner": False},
    {"name": "КД «Пожарники»", "level": "Начальный", "has_partner": False},
    {"name": "Вальс «Графа Толстого»", "level": "Средний", "has_partner": False},
    {"name": "Ирландская полька", "level": "Начальный", "has_partner": False},
    {"name": "Вальс «Катрин»", "level": "Средний", "has_partner": False},
    {"name": "Романи полька", "level": "Начальный", "has_partner": False},
    {"name": "Вальс «Прогулка»", "level": "Начальный", "has_partner": False},
    {"name": "Шотланский Вальс", "level": "Начальный", "has_partner": False},
    {"name": "Бретонская линейная джига", "level": "Начальный", "has_partner": False},
    {"name": "Вальс «Анастасия»", "level": "Средний", "has_partner": False},
    {"name": "КД «Русский Марш»", "level": "Средний", "has_partner": False},
    {"name": "БФ Вальс", "level": "Продвинутый", "has_partner": False},
    {"name": "Вальс «Калейдоскоп»", "level": "Средний", "has_partner": False},
    {"name": "Вальс «Ветер с гор»", "level": "Средний", "has_partner": False},
    {"name": "КД «Роувелл»", "level": "Продвинутый", "has_partner": False},
    {"name": "Вальс «Надежда»", "level": "Средний", "has_partner": False},
    {"name": "Блюз", "level": "Средний", "has_partner": False},
    {"name": "Вальс «Память»", "level": "Средний", "has_partner": False},
    {"name": "Порушка", "level": "Начальный", "has_partner": False},
]

LEVEL_ORDER = ["Начальный", "Средний", "Продвинутый"]
